# Generated by Django 4.2.13 on 2024-06-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('eta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='alloc.batch')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloc.orderline')),
            ],
        ),
    ]
