# Generated by Django 4.2.13 on 2024-06-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alloc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table='batch',
        ),
    ]
