# Generated by Django 4.2.13 on 2024-06-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alloc', '0002_alter_batch_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table=None,
        ),
    ]
